__title__ = 'DeFiLlama-Curl'
__description__ = 'Unofficial Python wrapper for DeFi Llama API client using the PyCurl module.'
__url__ = 'https://github.com/the-praxs/DeFiLlama'
__version__ = '2.0.1'
__author__ = 'Pratyush Shukla'
__author_email__ = 'ps4534@nyu.edu'
__license__ = 'Apache License 2.0'
__copyright__ = 'Copyright 2022 Pratyush Shukla'
